const Data = [{
    id: 1,
    title: `A Court of Mist and Fury`,
    secondary_id: `recommended`,
    author: `Sarah J. Maas`,
    img: `https://covers.openlibrary.org/b/id/13325541-L.jpg`,
    href: `https://openlibrary.org/works/OL17860744W/A_Court_of_Mist_and_Fury#starRatingSection`,
    description: `Feyre has undergone more trials than one human woman can carry in her heart. Though she's now been granted the powers and lifespan of the High Fae, she is haunted by her time Under the Mountain and the terrible deeds she performed to save the lives of Tamlin and his people.
    As her marriage to Tamlin approaches, Feyre's hollowness and nightmares consume her. She finds herself split into two different people: one who upholds her bargain with Rhysand, High Lord of the feared Night Court, and one who lives out her life in the Spring Court with Tamlin. While Feyre navigates a dark web of politics, passion, and dazzling power, a greater evil looms. She might just be the key to stopping it, but only if she can harness her harrowing gifts, heal her fractured soul, and decide how she wishes to shape her future-and the future of a world in turmoil.
    Bestselling author Sarah J. Maas's masterful storytelling brings this second book in her dazzling, sexy, action-packed series to new heights.
    `,
    ratings: `142`,
    have_read: `141`,
    publish_data: `2020`,
    publisher: `Bloomsbury Publishing`,
    language: `English`,
    pages: 640
}, {
    id: 2,
    title: `A Game of Thrones`,
    secondary_id: `recommended`,
    author: `George R. R. Martin`,
    img: `https://covers.openlibrary.org/b/id/11291394-L.jpg`,
    href: `https://openlibrary.org/works/OL257943W/A_Game_of_Thrones`,
    description: [`A GAME OF THRONES`, `Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister and supernatural forces are massing beyond the kingdom’s protective Wall. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the land they were born to. Sweeping from a land of brutal cold to a distant summertime kingdom of epicurean plenty, here is a tale of lords and ladies, soldiers and sorcerers, assassins and bastards, who come together in a time of grim omens.
    `, `Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister and supernatural forces are massing beyond the kingdom’s protective Wall. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the land they were born to. Sweeping from a land of brutal cold to a distant summertime kingdom of epicurean plenty, here is a tale of lords and ladies, soldiers and sorcerers, assassins and bastards, who come together in a time of grim omens.
    `],
    ratings: `338`,
    have_read: `387`,
    publish_data: `May 28, 2002`,
    publisher: `Bantam Books`,
    language: `English`,
    pages: 704
}, {
    id: 3,
    title: `Teias de charlotte`,
    secondary_id: `recommended`,
    author: `E. B. White`,
    img: `https://covers.openlibrary.org/b/id/8311468-L.jpg`,
    href: `https://openlibrary.org/works/OL483391W/Charlotte%27s_Web`,
    description: [`Wilbur the pig is desolate when he discovers that he is destined to be the farmer's Christmas dinner until his spider friend, Charlotte, decides to help him.
    `],
    ratings: `207`,
    have_read: `278`,
    publish_data: `2002`,
    publisher: `HarperCollins Publishers`,
    language: `Portuguese`,
    pages: 216
},
{
    id: 4,
    title: `The Cruel Prince`,
    secondary_id: `recommended`,
    author: `Holly Black`,
    img: `https://covers.openlibrary.org/b/id/13162571-L.jpg`,
    href: `https://openlibrary.org/works/OL21178912W/El_Pr%C3%ADncipe_Cruel`,
    description: [`Jude was seven when her parents were murdered and she and her two sisters were stolen away to live in the treacherous High Court of Faerie. Ten years later, Jude wants nothing more than to belong there, despite her mortality. But many of the fey despise humans. Especially Prince Cardan, the youngest and wickedest son of the High King.`,
        `To win a place at the Court, she must defy him–and face the consequences.`, `To win a place at the Court, she must defy him–and face the consequences.
                   ` ],
    ratings: `38`,
    have_read: `21`,
    publish_data: `2018`,
    publisher: `Hot Key Books`,
    language: `English`,
    pages: 385
}, {
    id: 5,
    title: `Think Like a Monk`,
    secondary_id: `recommended`,
    author: `Jay Shetty`,
    img: `https://covers.openlibrary.org/b/id/10476383-L.jpg`,
    href: `https://openlibrary.org/works/OL21237606W/Think_Like_a_Monk`,
    description: [`Jay Shetty, social media superstar and host of the #1 podcast On Purpose, distills the timeless wisdom he learned as a monk into practical steps`,
        `Shetty grew up in a family where you could become one of three things—a doctor, a lawyer, or a failure. His family was convinced he had chosen option three: instead of attending his college graduation ceremony, he headed to India to become a monk, to meditate every day for four to eight hours, and devote his life to helping others. After three years, one of his teachers told him that he would have more impact on the world if he left the monk’s path to share his experience and wisdom with others. Heavily in debt, and with no recognizable skills on his résumé, he moved back home in north London with his parents.`,
        `Shetty reconnected with old school friends—many working for some of the world’s largest corporations—who were experiencing tremendous stress, pressure, and unhappiness, and they invited Shetty to coach them on well-being, purpose, and mindfulness. Since then, Shetty has become one of the world’s most popular influencers. *In 2017, he was named in the Forbes magazine 30-under-30 for being a game-changer in the world of media. In 2018, he had the #1 video on Facebook with over 360 million views. His social media following totals over 38 million, he has produced over 400 viral videos which have amassed more than 8 billion views, and his podcast, On Purpose, is consistently ranked the world’s #1 Health and Wellness podcast.`],
    ratings: `49`,
    have_read: `29`,
    publish_data: `Sep 08, 2020`,
    publisher: `Simon & Schuster Audio`,
    language: `English`,
    pages: 228
},
{
    id: 6,
    title: `The Psychology of Money`,
    secondary_id: `recommended`,
    author: `Morgan Housel`,
    img: `https://covers.openlibrary.org/b/id/12824425-L.jpg`,
    href: `https://openlibrary.org/works/OL21640039W/The_Psychology_of_Money`,
    description: [`Timeless lessons on wealth, greed, and happiness doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically considered to involve a lot of mathematical calculations, where data and formulae tell us exactly what to do. But in the real world, people don’t make financial decisions on a spreadsheet. They make them at the dinner table, or in a meeting room, where personal history, your unique view of the world, ego, pride, marketing, and odd incentives are scrambled together. In the psychology of money, the author shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life’s most important matters.    `],
    ratings: `80`,
    have_read: `49`,
    publish_data: `Sep 08, 2020`,
    publisher: `Harriman House`,
    language: `English`,
    pages: 256
},
{
    id: 7,
    title: `Red, White & Royal Blue`,
    secondary_id: `recommended`,
    author: `Casey McQuiston and Ramon De Ocampo`,
    img: `https://covers.openlibrary.org/b/id/8311468-L.jpg`,
    href: `https://openlibrary.org/works/OL20090688W/Red_White_Royal_Blue`,
    description: [`When his mother became President of the United States, Alex Claremont-Diaz was promptly cast as the American equivalent of a young royal. Handsome, charismatic, genius--his image is pure millennial-marketing gold for the White House. There's only one problem: Alex has a beef with an actual prince, Henry, across the pond. And when the tabloids get hold of a photo involving an Alex/Henry altercation, U.S./British relations take a turn for the worse.`,
        `Heads of family and state and other handlers devise a plan for damage control: Stage a truce between the two rivals. What at first begins as a fake, Instagrammable friendship grows deeper, and more dangerous, than either Alex or Henry could have imagined. Soon Alex finds himself hurtling into a secret romance with a surprisingly unstuffy Henry that could derail the presidential campaign and upend two nations. It raises the question: Can love save the world after all? Where do we find the courage, and the power, to be the people we are meant to be? And how can we learn to let our true colors shine through?`],
    ratings: `62`,
    have_read: `56`,
    publish_data: `2019`,
    publisher: `St. Martin's Griffin`,
    language: `English`,
    pages: 421
},
{
    id: 8,
    title: `The Subtle Art of Not Giving a Fuck`,
    secondary_id: `recommended`,
    author: `Mark Manson`,
    img: `https://covers.openlibrary.org/b/id/8231990-M.jpg`,
    href: `https://openlibrary.org/works/OL17590212W/The_Subtle_Art_of_Not_Giving_a_F%2Ack`,
    description: [`This breakout, mega bestseller is the self-help book for people who hate self-help. It’s as much a pat on the back as a slap in the face. It’s the first truly no BS guide to flourishing in a crazy, crazy world—a truly counterintuitive approach to living a good life.`],
    ratings: `517`,
    have_read: `486`,
    publish_data: `2019`,
    publisher: `HarperLuxe`,
    language: `English`,
    pages: 256
},
{
    id: 9,
    title: `Little, Brown Book Group Limited`,
    secondary_id: `recommended`,
    author: `Tahereh Mafi`,
    img: `https://covers.openlibrary.org/b/id/7272906-L.jpg`,
    href: `https://openlibrary.org/works/OL16813331W/Ignite_Me`,
    description: [`A girl who has the touch to kill and only 2 guys who are able to touch her which one will she choose everyone's enemy or her childhood best friend. who gonna win the war the 'gifted' people or the army. Will she get her revenge on the enemy's father or will she die along the rest.`],
    ratings: `29`,
    have_read: `59`,
    publish_data: `February 4th 2014`,
    publisher: `HarperCollins, Harpercollins`,
    language: `English`,
    pages: 416
},
{
    id: 10,
    title: `Twisted Lies`,
    secondary_id: `recommended`,
    author: `Ana Huang`,
    img: `https://covers.openlibrary.org/b/id/12816871-L.jpg`,
    href: `https://covers.openlibrary.org/b/id/12816871-L.jpg`,
    ratings: `52`,
    have_read: `39`,
    publish_data: `2022`,
    publisher: `Little, Brown Book Group Limited`,
    language: `English`,
    pages: 216
}, {
    id: 11,
    secondary_id: `main_books`,
    title: `Chemistry`,
    category: `Science`,
    author: `Theodore L. Brown et.al`,
    description: [`The book provides the basis of modern chemistry that every student needs for their professional development and as preparation for more complex chemistry courses. It also offers features that facilitate learning and serve as a guide for students to acquire a conceptual understanding and the skills needed to solve problems. The first five chapters offer a microscopic and phenomenological view of chemistry, while the latter review the chemistry of nonmetals, metals, organic chemistry and biochemistry.`],
    img: `https://covers.openlibrary.org/b/id/9679987-L.jpg`,
    href: `https://openlibrary.org/works/OL15130687W/Chemistry?edition=key%3A/books/OL2396590M`,
    ratings: `20 `,
    have_read: `21`,
    publish_data: `1988`,
    publisher: `Prentice Hall`,
    language: `English`,
    pages: `1028`
}, {
    id: 12,
    secondary_id: `main_books`,
    title: `Biology`,
    category: `Science`,
    author: `Cecie Starr et.al`,
    description: [`We offer this book as a coherent account of the sweep of life's diversity and its underlying unity. Through its examples of problem solving and experiments, it shows the power of thinking critically about the natural world. It highlights key concepts, current understandings, and research trends for major fields of biological inquiry. It explains the structure and function of a broad sampling of organisms in enough detail so that students can develop a working vocabulary about life's parts and processes. - Page xvii. Throughout this book, you will come across many examples of how organisms are constructed, how they function, where they live, what they do. The examples support concepts which, when taken together, convey what "life" is.`],
    img: `https://covers.openlibrary.org/b/id/6383286-L.jpg`,
    href: `https://openlibrary.org/works/OL1975314W/Biology?edition=key%3A/books/OL2730544M`,
    ratings: `10`,
    have_read: `15`,
    publish_data: `1987`,
    publisher: `Wadsworth Pub. Co.`,
    language: `English`,
    pages: `776`
}, {
    id: 13,
    secondary_id: `main_books`,
    title: `21st Century Astronomy`,
    category: `Science`,
    author: `Jeffrey S. Hester et.al`,
    description: [`This edition doesn't have a description yet.`],
    img: `https://covers.openlibrary.org/b/id/11583475-L.jpg`,
    href: `https://openlibrary.org/works/OL21725900W/21st_Century_Astronomy?edition=key%3A/books/OL29570107M`,
    ratings: `1`,
    have_read: `1`,
    publish_data: `2010`,
    publisher: `Norton & Company, Incorporated, W. W.`,
    language: `English`,
    pages: `763`
}, {
    id: 14,
    secondary_id: `main_books`,
    title: `Out of the Silent Planet`,
    category: `Science`,
    author: `C. S. Lewis`,
    description: [`The first book in Lewis's Space Trilogy, Out of the Silent Planet tells the story of Dr. Elwin Ransom, a philologist who likes to explore the English countryside on foot. Seeking out a place to stay the night, he ends up at the estate of a colleague who is away in London. However, the house is not empty. Ransom stumbles upon the plot of a megalomaniacal scientist and his collaborator, who just happens to be an old schoolmate of Ransom's. Drugged, kidnapped, and wisked away in the scientists rocket to the planet Malacandra where he is to serve as a human sacrifice, Dr. Ransom escapes into the strange Malacandran wilderness pursued by his kidnappers and abandoning his hopes of returning to Earth.`,
        `Ransom discovers that the inhabitants of Malacandra are not what his kidnappers believed them to be. In his adventures in the often strangely beautiful, sometimes dangerous, and sometimes surprisingly familiar Malacandra and its inhabitants, Ransom uncovers information about the larger universe and Earth's place that suggest he has as much to discover about his home planet as he does about the alien Malacandra.`
    ],
    img: `https://covers.openlibrary.org/b/id/9321665-L.jpg`,
    href: `https://openlibrary.org/works/OL71166W/Out_of_the_Silent_Planet?edition=key%3A/books/OL16159927M`,
    ratings: `20`,
    have_read: `38`,
    publish_data: `1965`,
    publisher: `Macmillan`,
    language: `English`,
    pages: `160`
}, {
    id: 15,
    secondary_id: `main_books`,
    title: `Essential Maths`,
    category: `Mathematics`,
    author: `Sean McArdle`,
    description: [`This edition doesn't have a description yet. `],
    img: `https://covers.openlibrary.org/b/id/2584771-L.jpg`,
    href: `https://openlibrary.org/works/OL8838576W/Essential_Maths?edition=key%3A/books/OL10762324M`,
    ratings: `3`,
    have_read: `6`,
    publish_data: `May 24, 2004`,
    publisher: `Nelson Thornes Ltd`,
    language: `English`,
    pages: `32`
}, {
    id: 16,
    secondary_id: `main_books`,
    title: `Elementary linear algebra`,
    category: `Mathematics`,
    author: `Howard Anton and HA Anton`,
    description: [`This edition doesn't have a description yet. `],
    img: `https://covers.openlibrary.org/b/id/9577632-L.jpg`,
    href: `https://openlibrary.org/works/OL485862W/Elementary_linear_algebra?edition=key%3A/books/OL4892686M`,
    ratings: `5`,
    have_read: `6`,
    publish_data: `1977`,
    publisher: `Wiley`,
    language: `English`,
    pages: `336`
}, {
    id: 17,
    secondary_id: `main_books`,
    title: `Euclidis elementorum libri XV`,
    category: `Mathematics`,
    author: `Euclid`,
    description: [`The classic Heath translation, in a completely new layout with plenty of space and generous margins. An affordable but sturdy student and teacher sewn softcover edition in one volume, with minimal notes and a new index/glossar`],
    img: `https://covers.openlibrary.org/b/id/11868398-L.jpg`,
    href: `https://openlibrary.org/works/OL912133W/Elements?edition=ia%3Aeuclidiselemento01eucl`,
    ratings: `8`,
    have_read: `8`,
    publish_data: `1574`,
    publisher: `Apud Vincentium Accoltum`,
    language: `Latin`,
    pages: `250`
}, {
    id: 18,
    secondary_id: `main_books`,
    title: `The C Programming Languages`,
    category: `Programming`,
    author: `Brian W. Kernighan`,
    description: [`The authors present the complete guide to ANSI standard C language programming. Written by the developers of C, this new version helps readers keep up with the finalized ANSI standard for C while showing how to take advantage of C's rich set of operators, economy of expression, improved control flow, and data structures. The 2/E has been completely rewritten with additional examples and problem sets to clarify the implementation of difficult language constructs. For years, C programmers have let K&R guide them to building well-structured and efficient programs. Now this same help is available to those working with ANSI compilers. Includes detailed coverage of the C language plus the official C language reference manual for at-a-glance help with syntax notation, declarations, ANSI changes, scope rules, and the list goes on and on.`],
    img: `https://covers.openlibrary.org/b/id/5732572-L.jpg`,
    href: `https://openlibrary.org/books/OL2030445M/The_C_Programming_Language`,
    ratings: `4`,
    have_read: `7`,
    publish_data: `1988`,
    publisher: `Prentice Hall`,
    language: `English`,
    pages: `272`
}, {
    id: 19,
    secondary_id: `main_books`,
    title: `Software engineering`,
    category: `Programming`,
    author: `Roger S. Pressman and Bruce Maxim`,
    description: [`This edition doesn't have a description yet.`],
    img: `https://covers.openlibrary.org/b/id/10617761-L.jpg`,
    href: `https://openlibrary.org/works/OL284009W/Software_Engineering`,
    ratings: `3`,
    have_read: `3`,
    publish_data: `2005`,
    publisher: `McGraw-Hill`,
    language: `English`,
    pages: `880`
}, {
    id: 20,
    secondary_id: `main_books`,
    title: `Structured computer organization`,
    category: `Programming`,
    author: `Andrew S. Tanenbaum`,
    description: [`Structured Computer Organization, specifically written for undergraduate students, is a best-selling guide that provides an accessible introduction to computer hardware and architecture. This text will also serve as a useful resource for all computer professionals and engineers who need an overview or introduction to computer architecture.`],
    img: `https://covers.openlibrary.org/b/id/6570327-L.jpg`,
    href: `https://openlibrary.org/works/OL448894W/Tom_Clancy%27s_Net_Force`,
    ratings: `1`,
    have_read: `1`,
    publish_data: `1999`,
    publisher: `Prentice Hall`,
    language: `English`,
    pages: `669`
}, {
    id: 21,
    secondary_id: `main_books`,
    title: `The Art of Computer Programming: Volume 3`,
    category: `Programming`,
    author: `Donald Knuth`,
    description: [`This book forms a natural sequel to the material on information structures in Chapter 2 of Volume 1, because it adds the concept of linearly ordered data to the other basic structural ideas.`,
                   `The title 'Sorting and Searching' may sound as if this book is only for those systems programmers who are concerned with the preparation of general-purpose sorting routines or applications to information retrieval. But in fact the area of sorting and searching provides an ideal framework for discussing a wide variety of important general issues:`,
                   `How are good algorithms discovered? How can given algorithms and programs be improved? How can the efficiency of algorithms be analyzed mathematically? How can a person choose rationally between different algorithms for the same task? In what senses can algorithms be proved ''best possible''? How does the theory of computing interact with practical considerations? How can external memories like tapes, drums, or disks be used efficiently with large databases?` ],
    img: `https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRtw-H0EsjYiYEYVWQKfz8cdlt228tafiRmVEJyUB7xRzv7e1M4`,
    href: `https://openlibrary.org/works/OL257263W/The_Art_of_Computer_Programming`,
    ratings: `6`,
    have_read: `7`,
    publish_data: `1968`,
    publisher: `Addison-Wesley Pub. Co.`,
    language: `English`,
    pages: `unknown`
},{
    id: 22,
    secondary_id: `main_books`,
    title: `The wonderful world of Oz`,
    category: `Fiction`,
    author: `L. Frank Baum`,
    description: [`Over a century after its initial publication, The Wonderful Wizard of Oz is still captivating the hearts of countless readers. Come adventure with Dorothy and her three friends: the Scarecrow, the Tin Woodman, and the Cowardly Lion, as they follow the Yellow Brick Road to the Emerald City for an audience with the Great Oz, the mightiest Wizard in the land, and the only one that can return Dorothy to her home in Kansas.`],
    img: `https://covers.openlibrary.org/b/id/107689-L.jpg`,
    href: `https://openlibrary.org/works/OL18417W/The_Wonderful_Wizard_of_Oz`,
    ratings: `71`,
    have_read: `107`,
    publish_data: `1998`,
    publisher: `Penguin Books, Penguin Classics`,
    language: `English`,
    pages: `389`
},{
    id: 23,
    secondary_id: `main_books`,
    title: `Le Monde Perdu`,
    category: `Fiction`,
    author: `Arthur Conan Doyle`,
    description: [`Journalist Ed Malone is looking for an adventure, and that's exactly what he finds when he meets the eccentric Professor Challenger - an adventure that leads Malone and his three companions deep into the Amazon jungle, to a lost world where dinosaurs roam free.`],
    img: `https://covers.openlibrary.org/b/id/12284357-L.jpg`,
    href: `https://openlibrary.org/works/OL262460W/The_Lost_World`,
    ratings: `222`,
    have_read: `44`,
    publish_data: `1989`,
    publisher: `Laffont`,
    language: `French`,
    pages: `unknown`
},{
    id: 24,
    secondary_id: `main_books`,
    title: `The New Annotated Dracula`,
    category: `Fiction`,
    author: `Bram Stoker`,
    description: [`It tells the story of Dracula's attempt to move from Transylvania to England so he may find new blood and spread undead curse, and the battle between Dracula and a small group of men and women led by Professor Abraham Van Helsing.`],
    img: `https://covers.openlibrary.org/b/id/12750396-L.jpg`,
    href: `https://openlibrary.org/works/OL85892W/Dracula`,
    ratings: `105`,
    have_read: `175`,
    publish_data: `2008`,
    publisher: `W.W. Norton`,
    language: `English`,
    pages: `672`
},{
    id: 25,
    secondary_id: `main_books`,
    title: `Brave new world`,
    category: `Fiction`,
    author: `Aldous Huxley`,
    description: [`Originally published in 1932, this outstanding work of literature is more crucial and relevant today than ever before. Cloning, feel-good drugs, antiaging programs, and total social control through politics, programming, and media -- has Aldous Huxley accurately predicted our future? With a storyteller's genius, he weaves these ethical controversies in a compelling narrative that dawns in the year 632 AF (After Ford, the deity). When Lenina and Bernard visit a savage reservation, we experience how Utopia can destroy humanity. A powerful work of speculative fiction that has enthralled and terrified readers for generations, Brave New World is both a warning to be heeded and thought-provoking yet satisfying entertainment.`],
    img: `https://covers.openlibrary.org/b/id/10993168-L.jpg`,
    href: `https://openlibrary.org/works/OL64468W/Brave_New_World`,
    ratings: `303`,
    have_read: `433`,
    publish_data: `2015`,
    publisher: `The Secret Bookshelf`,
    language: `English`,
    pages: `359`
},{
    id: 26,
    secondary_id: `main_books`,
    title: `Adventures of Huckleberry Finn`,
    category: `Literature`,
    author: `Mark Twain`,
    description: [`Adventures of Huckleberry Finn or as it is known in more recent editions, The Adventures of Huckleberry Finn, is a novel by American author Mark Twain, which was first published in the United Kingdom in December 1884 and in the United States in February 1885.
    `, `Commonly named among the Great American Novels, the work is among the first in major American literature to be written throughout in vernacular English, characterized by local color regionalism. It is told in the first person by Huckleberry "Huck" Finn, the narrator of two other Twain novels (Tom Sawyer Abroad and Tom Sawyer, Detective) and a friend of Tom Sawyer. It is a direct sequel to The Adventures of Tom Sawyer.`],
    img: `https://covers.openlibrary.org/b/id/12903616-L.jpg`,
    href: `https://openlibrary.org/works/OL53908W/Adventures_of_Huckleberry_Finn`,
    ratings: `119`,
    have_read: `175`,
    publish_data: `1973-11`,
    publisher: `Washington Square Press Enriched Classics/Pocket Books`,
    language: `English`,
    pages: `374`
},{
    id: 27,
    secondary_id: `main_books`,
    title: `Treasure Island`,
    category: `Literature`,
    author: `Robert Louis Stevenson`,
    description: [`Traditionally considered a coming-of-age story, Treasure Island is an adventure tale known for its atmosphere, characters and action, and also as a wry commentary on the ambiguity of morality — as seen in Long John Silver — unusual for children's literature then and now. It is one of the most frequently dramatized of all novels. The influence of Treasure Island on popular perceptions of pirates is enormous, including treasure maps marked with an "X", schooners, the Black Spot, tropical islands, and one-legged seamen carrying parrots on their shoulders`],
    img: `https://covers.openlibrary.org/b/id/12819044-L.jpg`,
    href: `https://openlibrary.org/works/OL24034W/Treasure_Island`,
    ratings: `62`,
    have_read: `99`,
    publish_data: `2016`,
    publisher: `Vintage`,
    language: `English`,
    pages: `324`
},{
    id: 28,
    secondary_id: `main_books`,
    title: `Little Women`,
    category: `Literature`,
    author: `Louisa May Alcott`,
    description: [`Chronicles the joys and sorrows of the four March sisters as they grow into young ladies in nineteenth-century New England.`],
    img: `https://covers.openlibrary.org/b/id/12811475-L.jpg`,
    href: `https://openlibrary.org/works/OL29983W/Little_Women`,
    ratings: `78`,
    have_read: `18`,
    publish_data: `1994`,
    publisher: `Longmeadow Press`,
    language: `English`,
    pages: `288`
},{
    id: 29,
    secondary_id: `main_books`,
    title: `Oliver Twist`,
    category: `Literature`,
    author: `Louisa May Alcott`,
    description: [`ONE OF THE MOST SWIFTLY MOVING AND unified of Charles Dickens's great novels, Oliver Twist is also famous for its re-creation—through the splendidly realized figures of Fagin, Nancy, the Artful Dodger, and the evil Bill Sikes— of the vast London underworld of pickpockets, thieves, prostitutes, and abandoned children. Victorian critics took Dickens to task for render- ing this world in such a compelling, believable way, but readers over the last 150 years have delivered an alternative judgment by making this story of the orphaned Oliver Twist one of its author's most loved works.`],
    img: `https://covers.openlibrary.org/b/id/9281234-L.jpg`,
    href: `https://openlibrary.org/works/OL8193478W/Oliver_Twist`,
    ratings: `20`,
    have_read: `40`,
    publish_data: `1992`,
    publisher: `Alfred A. Knopf`,
    language: `English`,
    pages: `427`
}


]


export default Data;